name: Deploy Frontend to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. COPIAR LOS ARCHIVOS NUEVOS A LA EC2
      # Envía tu código limpio desde GitHub a la carpeta del servidor
      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 18.219.229.98
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "., !.git"
          target: "/hurammy"

      # 2. CONECTARSE POR SSH, COMPILAR Y ACTUALIZAR DOCKER
      - name: SSH and Update Container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 18.219.229.98
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /hurammy
            
            # Detener y eliminar el contenedor viejo para liberar el puerto 8080
            sudo docker stop shortvideo-frontend || true
            sudo docker rm shortvideo-frontend || true
            
            # Compilar la nueva imagen usando los archivos recién copiados
            sudo docker build -t hurammy-frontend:latest .
            
            # Levantar el frontend en el puerto 8080 (el puerto exacto que busca tu Nginx)
            sudo docker run -d --name shortvideo-frontend -p 8080:80 --restart always hurammy-frontend:latest
