name: Deploy Frontend to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. COPIAR LOS CAMBIOS A LA EC2
      # Esto transfiere tu código actualizado desde GitHub hacia la carpeta /hurammy en tu servidor
      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 18.219.229.98
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/hurammy"

      # 2. COMPILAR Y LEVANTAR EN LA EC2
      - name: SSH and Update Container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 18.219.229.98
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /hurammy
            
            # Detener y eliminar el contenedor viejo para evitar conflictos de nombre
            sudo docker stop shortvideo-frontend || true
            sudo docker rm shortvideo-frontend || true
            
            # Compilar la imagen usando los archivos nuevos que acabamos de copiar
            sudo docker build -t hurammy-frontend:latest .
            
            # Levantar el contenedor en los puertos correspondientes
            sudo docker run -d --name shortvideo-frontend -p 80:80 -p 443:443 --restart always hurammy-frontend:latest
